### ISSUE TITLE
Continuation of the project

### ISSUE THREAD

**Issue by Getty** [Jusas/SQLite3UE4#15]
Hiho,

As I needed this code, but also wanted to fix the "static library" situation (so the requirement to precompile the lib), enforced me a bit to make an own version which I would like to continue working on. As it is nearly all based on your previous code, I just wanted to ask if that is ok with you? I already added and filled (with working version of how i need it) under https://github.com/cindustries/unreal-sqlite3 I also took your image for now, but I target to make a new one. I didn't promoted it yet.

Thanks in advance for the reply!

**Comment by Jusas** [comment]
As far as I'm concerned, feel free to do whatever you want with the code.
The repo is no longer being maintained, so I'm glad you still found it
useful. It's great to see that people have picked up the code and continued
the good work!

The code is all free to do as you like, enjoy :-)
- Jussi

**Comment by Getty** [comment]
Great! If you want then you might also could put a link to my repo on yours so that people directly find the freshly maintained one and so the problems land on my table ;)

**Comment by Getty** [comment]
Oh forget that, i am an idiot, i just found out that there is this further fork <facepalm>, all that chaos! Good that I started http://unreal.directory/ so that at some point this can get managed

**Comment by Getty** [comment]
Hey thanks, thats great for new users!
